SELECT MIN("TOTAL_STEPS") AS MIN_TOTAL_STEPS,
      MAX("TOTAL_STEPS") AS MAX_TOTAL_STEPS,
      AVG("TOTAL_STEPS") AS MEAN_TOTAL_STEPS,
      percentile_cont(0.5) WITHIN GROUP (ORDER BY "TOTAL_STEPS") as MEDIAN_TOTAL_STEPS
FROM "DAILY_ACTIVITY"
