INSERT INTO public."HOURLY_ACTIVITY"(
	"ID", 
	"ACTIVITY_HOUR", 
	"CALORIES", 
	"STEP_TOTAL", 
	"TOTAL_INTENSITY", 
	"AVERAGE_INTENSITY")
SELECT HC."ID", 
	HC."ACTIVITY_HOUR", 
	HC."CALORIES",
	HS."STEP_TOTAL", 
	HI."TOTAL_INTENSITY", 
	HI."AVERAGE_INTENSITY"
FROM "HOURLY_CALORIES" AS HC
INNER JOIN "HOURLY_INTENSITY" AS HI ON HI."ID" = HC."ID"
	AND HI."ACTIVITY_HOUR" = HC."ACTIVITY_HOUR"
INNER JOIN "HOURLY_STEPS" AS HS ON HS."ID" = HC."ID"
	AND HS."ACTIVITY_HOUR" = HC."ACTIVITY_HOUR";
 