INSERT INTO public."HOURLY_ACTIVITY"(
	"ID", 
	"ACTIVITY_HOUR", 
	"CALORIES", 
	"STEP_TOTAL", 
	"TOTAL_INTENSITY", 
	"AVERAGE_INTENSITY")
SELECT HC."ID", 
	HC."ACTIVITY_HOUR", 
	COALESCE(HC."CALORIES", 0),
	COALESCE(HS."STEP_TOTAL", 0), 
	COALESCE(HI."TOTAL_INTENSITY", 0), 
	COALESCE(HI."AVERAGE_INTENSITY", 0)
FROM "HOURLY_CALORIES" AS HC
INNER JOIN "HOURLY_INTENSITY" AS HI ON HI."ID" = HC."ID"
	AND HI."ACTIVITY_HOUR" = HC."ACTIVITY_HOUR"
INNER JOIN "HOURLY_STEPS" AS HS ON HS."ID" = HC."ID"
	AND HS."ACTIVITY_HOUR" = HC."ACTIVITY_HOUR";
 